{% set name = "pytest-chalice" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f357d53d123b201c9e6235f67f8ef6a4310bdfea67f75ee4dbe4aed0f19e319a
  patches:
    - setuptools_scm.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - chalice
    - pytest

test:
  imports:
    - pytest_chalice
  commands:
    - chalice --help

about:
  home: https://github.com/studio3104/pytest-chalice
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A set of py.test fixtures for AWS Chalice
  doc_url: https://pypi.org/project/pytest-chalice/#description
  dev_url: https://github.com/studio3104/pytest-chalice

extra:
  recipe-maintainers:
    - oblute
    - mwilson8
    - benhuff
